Add actix-governor middleware to auth API
Trioxidation/Triox pull request #39
Opened 2021-07-08 17:35 UTC by AaronErhardt

+ Add actix-governor middleware to auth API
+ Minor fix of docs in main.rs

2021-07-08 18:03 UTC, realaravinth requested changes

2021-07-08 18:03 UTC, realaravinth commented on src/middleware/rate_limit.rs
> +    static ref AUTH_LIMITER: GovernorConfig = GovernorConfig::secure();
IMO there are situations where IP based rate limiting is ineffective, can you make this optional? Also, please make the rate limiter configurable. 

Perhaps adding sections to `config::AppConfg.server` for accepting rate limit configurations and making it an `Option<T>` will address both issues

2021-07-08 21:18 UTC, AaronErhardt commented on src/middleware/rate_limit.rs
> +    static ref AUTH_LIMITER: GovernorConfig = GovernorConfig::secure();
With the latest commits the rate limiting should be configurable. I enabled it by default as it still protects against simpler DoS attacks. And even when enabled it's only enabled for the auth API which should be fine because that's the most vulnerable API of the server as hashing passwords is probably by far the most expansive operation.

2021-07-09 06:09 UTC, realaravinth requested changes

2021-07-09 07:43 UTC, AaronErhardt commented on src/api/v1/auth.rs
> +)] // wrap = "crate::CheckLogin")]
That's already changed by the latest commits

2021-07-09 07:45 UTC, realaravinth commented on src/api/v1/auth.rs
> +)] // wrap = "crate::CheckLogin")]
oh, sorry about that!

2021-07-09 07:53 UTC, AaronErhardt commented on src/api/v1/auth.rs
> +            web::scope("")
Mhh, what would you consider foolproof? You mean by using wrap in my_codegen attributes? That can hardly made optional, right?

Yet I think the check for test config should be in `src/api/v1/auth.rs` rather than `src/config.rs`. The general problem is that getting tests to work with the rate limiter requires some hacks and actix_governor already has tests for itself.

2021-07-09 08:12 UTC, realaravinth commented on src/api/v1/auth.rs
> +            web::scope("")
I'm concerned about 
- the middleware not working due to scope and route mismatch 
- middleware leaking into the broader scope

I've run into both of these bugs previously. We'll need tests to detect errors, perhaps a seperate test run in the CI with the rate limiter turned on. And for the scope and route mismatch, I was thinking about something like this:

```rust
const ACTIVE: bool = true;
const ROUTE: &str = "/scope/get/";

#[my_codegen::get(path = "get_route()", wrap = "get_middleware()")]
async fn h1() -> impl Responder {
    "Handler 1"
}

fn get_route() -> &'static str {
    if ACTIVE {
        "/"
    } else {
        ROUTE
    }
}

fn get_scope() -> &'static str {
    if ACTIVE {
        if ROUTE.ends_with('/') {
            &ROUTE[0..ROUTE.len() - 1]
        } else {
            ROUTE
        }
    } else {
        ROUTE
    }
}

fn services(cfg: &mut actix_web::web::ServiceConfig) {
    println!("test");
    cfg.service(h2);
    if ACTIVE {
        cfg.service(
            web::scope(get_scope())
                .wrap(actix_web::middleware::NormalizePath::new(
                    actix_web::middleware::TrailingSlash::Always,
                ))
                .service(h1)
                .wrap_fn(|req, srv| {
                    println!("Hits middleware");
                    srv.call(req).map(|res| {
                        println!("Middleware hit");
                        res
                    })
                }),
        );
    } else {
        cfg.service(h1);
    }
}
```
It's bloated but the only way you can contain a middleware to scope is by assigning a scope to it, an empty scope risks leakage.

2021-07-09 08:25 UTC, AaronErhardt commented on src/api/v1/auth.rs
> +            web::scope("")
Makes sense. I just thought maybe something like this could be an option as well:

```rust
#[my_codegen::get(path = "get_route()", wrap_optional = "get_optional_middleware()")]
async fn h1() -> impl Responder {
    "Handler 1"
}
```

Where `get_optional_middleware()` simply returns `Option<Middleware>`. I don't know how hard is would be to implement this on the my_codegen part but that'd be a lot cleaner.

2021-07-15 14:21 UTC, realaravinth requested changes

2021-07-15 14:21 UTC, realaravinth commented on src/middleware/rate_limit.rs
> +        if gov_cfg.is_none() {
If I understand this correctly, `actix-governor` validates configuration and returns `None` if the config is invalid. In such a case, wouldn't be more appropriate to call `unwrap()` and crash?

2021-07-15 14:31 UTC, AaronErhardt commented on src/middleware/rate_limit.rs
> +        if gov_cfg.is_none() {
I guess, you're right. If someone accidentally used invalid values in the config it's probably better to panic than emitting a log message which might be overlooked.

2021-07-15 15:21 UTC, AaronErhardt commented on src/middleware/rate_limit.rs
> +        if gov_cfg.is_none() {
I just realized that panicing inside lazy-static isn't a very good idea, at least regarding the middleware initialization. It won't shut down the application but instead all worker threads will panic due to the poisoned Once. Panicing inside the AppConfig::new() would be an option but that'd mess up the config a bit. I made it work but it's not pretty. Do you have a better idea?
I can commit the changes if you want to see it though.

2021-07-15 15:25 UTC, realaravinth commented on src/middleware/rate_limit.rs
> +        if gov_cfg.is_none() {
You can try to initialize the configuration before entering the `HttpServer` closure, if everything checks out the server will be spawned and use the lazily initialized object while the test object is discarded.

2021-07-15 16:26 UTC, realaravinth approved these changes
Awesome! :tada:

2021-07-15 16:30 UTC, merged

2021-07-15 16:36 UTC, realaravinth commented
gg